//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.03 at 02:16:24 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.springbyexample.org/person/schema/beans")
package org.springbyexample.person.schema.beans;
