//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.25 at 12:13:07 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ws.cdyne.com/WeatherWS/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.cdyne.ws.weatherws;
