//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.02 at 08:51:44 AM CST 
//


package com.xignite.services;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.xignite.services package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GlobalQuote_QNAME = new QName("http://www.xignite.com/services/", "GlobalQuote");
    private final static QName _Header_QNAME = new QName("http://www.xignite.com/services/", "Header");
    private final static QName _Ticks_QNAME = new QName("http://www.xignite.com/services/", "Ticks");
    private final static QName _ArrayOfGlobalQuote_QNAME = new QName("http://www.xignite.com/services/", "ArrayOfGlobalQuote");
    private final static QName _SingleTick_QNAME = new QName("http://www.xignite.com/services/", "SingleTick");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.xignite.services
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CommonTick }
     * 
     */
    public CommonTick createCommonTick() {
        return new CommonTick();
    }

    /**
     * Create an instance of {@link Tick }
     * 
     */
    public Tick createTick() {
        return new Tick();
    }

    /**
     * Create an instance of {@link Ticks }
     * 
     */
    public Ticks createTicks() {
        return new Ticks();
    }

    /**
     * Create an instance of {@link GetGlobalTickResponse }
     * 
     */
    public GetGlobalTickResponse createGetGlobalTickResponse() {
        return new GetGlobalTickResponse();
    }

    /**
     * Create an instance of {@link GetGlobalTick }
     * 
     */
    public GetGlobalTick createGetGlobalTick() {
        return new GetGlobalTick();
    }

    /**
     * Create an instance of {@link GetGlobalTicks }
     * 
     */
    public GetGlobalTicks createGetGlobalTicks() {
        return new GetGlobalTicks();
    }

    /**
     * Create an instance of {@link GetGlobalRealTimeQuotes }
     * 
     */
    public GetGlobalRealTimeQuotes createGetGlobalRealTimeQuotes() {
        return new GetGlobalRealTimeQuotes();
    }

    /**
     * Create an instance of {@link GlobalQuote }
     * 
     */
    public GlobalQuote createGlobalQuote() {
        return new GlobalQuote();
    }

    /**
     * Create an instance of {@link SingleTick }
     * 
     */
    public SingleTick createSingleTick() {
        return new SingleTick();
    }

    /**
     * Create an instance of {@link Security }
     * 
     */
    public Security createSecurity() {
        return new Security();
    }

    /**
     * Create an instance of {@link GetGlobalRealTimeQuoteResponse }
     * 
     */
    public GetGlobalRealTimeQuoteResponse createGetGlobalRealTimeQuoteResponse() {
        return new GetGlobalRealTimeQuoteResponse();
    }

    /**
     * Create an instance of {@link GetGlobalTicksResponse }
     * 
     */
    public GetGlobalTicksResponse createGetGlobalTicksResponse() {
        return new GetGlobalTicksResponse();
    }

    /**
     * Create an instance of {@link GetGlobalRealTimeQuotesResponse }
     * 
     */
    public GetGlobalRealTimeQuotesResponse createGetGlobalRealTimeQuotesResponse() {
        return new GetGlobalRealTimeQuotesResponse();
    }

    /**
     * Create an instance of {@link Common }
     * 
     */
    public Common createCommon() {
        return new Common();
    }

    /**
     * Create an instance of {@link Header }
     * 
     */
    public Header createHeader() {
        return new Header();
    }

    /**
     * Create an instance of {@link ArrayOfGlobalQuote }
     * 
     */
    public ArrayOfGlobalQuote createArrayOfGlobalQuote() {
        return new ArrayOfGlobalQuote();
    }

    /**
     * Create an instance of {@link CommonDAObject }
     * 
     */
    public CommonDAObject createCommonDAObject() {
        return new CommonDAObject();
    }

    /**
     * Create an instance of {@link ArrayOfTick }
     * 
     */
    public ArrayOfTick createArrayOfTick() {
        return new ArrayOfTick();
    }

    /**
     * Create an instance of {@link GetGlobalRealTimeQuote }
     * 
     */
    public GetGlobalRealTimeQuote createGetGlobalRealTimeQuote() {
        return new GetGlobalRealTimeQuote();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GlobalQuote }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.xignite.com/services/", name = "GlobalQuote")
    public JAXBElement<GlobalQuote> createGlobalQuote(GlobalQuote value) {
        return new JAXBElement<GlobalQuote>(_GlobalQuote_QNAME, GlobalQuote.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Header }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.xignite.com/services/", name = "Header")
    public JAXBElement<Header> createHeader(Header value) {
        return new JAXBElement<Header>(_Header_QNAME, Header.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Ticks }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.xignite.com/services/", name = "Ticks")
    public JAXBElement<Ticks> createTicks(Ticks value) {
        return new JAXBElement<Ticks>(_Ticks_QNAME, Ticks.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfGlobalQuote }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.xignite.com/services/", name = "ArrayOfGlobalQuote")
    public JAXBElement<ArrayOfGlobalQuote> createArrayOfGlobalQuote(ArrayOfGlobalQuote value) {
        return new JAXBElement<ArrayOfGlobalQuote>(_ArrayOfGlobalQuote_QNAME, ArrayOfGlobalQuote.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SingleTick }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.xignite.com/services/", name = "SingleTick")
    public JAXBElement<SingleTick> createSingleTick(SingleTick value) {
        return new JAXBElement<SingleTick>(_SingleTick_QNAME, SingleTick.class, null, value);
    }

}
